# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name:  Install Google Chrome # Using shell script to install Google Chrome
      run:   |
              chmod +x ./scripts/InstallChrome.sh
                          ./scripts/InstallChrome.sh 
    - name: Build with Maven
      run: mvn clean test --file pom.xml
    - name: Copy cucumber.json
      run: |
          cp target/cucumber/cucumber.json target/
      
    - name: Commit Files Report # transfer the new html files back into the repository
      run: |
          git config --local user.name "viskiarditia"
          git add ./report
          git commit -m "Updating the repository report"
    
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
